/* Generated By:JavaCC: Do not edit this line. MemcacheParserTreeConstants.java Version 5.0 */
package hierophant.memcache.jjt;

public interface MemcacheParserTreeConstants
{
  public int JJTCOMMAND = 0;
  public int JJTSTORAGECOMMAND = 1;
  public int JJTCREATESTORAGECOMMAND = 2;
  public int JJTRETRIEVALCOMMAND = 3;
  public int JJTDELETECOMMAND = 4;
  public int JJTVERSIONCOMMAND = 5;
  public int JJTKEY = 6;
  public int JJTFLAGS = 7;
  public int JJTTIME = 8;
  public int JJTLENGTH = 9;
  public int JJTNOREPLY = 10;


  public String[] jjtNodeName = {
    "Command",
    "StorageCommand",
    "createStorageCommand",
    "RetrievalCommand",
    "DeleteCommand",
    "VersionCommand",
    "Key",
    "Flags",
    "Time",
    "Length",
    "Noreply",
  };
}
/* JavaCC - OriginalChecksum=f0038c3e3f1fdbb49e94cb440d9392e3 (do not edit this line) */
