/* Generated By:JJTree&JavaCC: Do not edit this line. MemcacheParserConstants.java */
package hierophant.memcache.jjt;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MemcacheParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int FLAGS = 6;
  /** RegularExpression Id. */
  int TIME = 7;
  /** RegularExpression Id. */
  int LENGTH = 8;
  /** RegularExpression Id. */
  int CREMENT_VALUE = 9;
  /** RegularExpression Id. */
  int CAS_UNIQUE = 10;
  /** RegularExpression Id. */
  int SET_STATEMENT = 11;
  /** RegularExpression Id. */
  int ADD_STATEMENT = 12;
  /** RegularExpression Id. */
  int REPLACE_STATEMENT = 13;
  /** RegularExpression Id. */
  int APPEND_STATEMENT = 14;
  /** RegularExpression Id. */
  int PREPEND_STATEMENT = 15;
  /** RegularExpression Id. */
  int CAS_STATEMENT = 16;
  /** RegularExpression Id. */
  int STORAGE_STATEMENT = 17;
  /** RegularExpression Id. */
  int STORAGE_COMMAND = 18;
  /** RegularExpression Id. */
  int RETRIEVAL_STATEMENT = 19;
  /** RegularExpression Id. */
  int RETRIEVAL_COMMAND = 20;
  /** RegularExpression Id. */
  int DELETE_STATEMENT = 21;
  /** RegularExpression Id. */
  int DELETE_COMMAND = 22;
  /** RegularExpression Id. */
  int INCREMENT_STATEMENT = 23;
  /** RegularExpression Id. */
  int INCREMENT_COMMAND = 24;
  /** RegularExpression Id. */
  int DECREMENT_STATEMENT = 25;
  /** RegularExpression Id. */
  int DECREMENT_COMMAND = 26;
  /** RegularExpression Id. */
  int STATISTICS_STATEMENT = 27;
  /** RegularExpression Id. */
  int STATISTICS_OPTION = 28;
  /** RegularExpression Id. */
  int STATISTICS_COMMAND = 29;
  /** RegularExpression Id. */
  int FLUSH_STATEMENT = 30;
  /** RegularExpression Id. */
  int FLUSH_COMMAND = 31;
  /** RegularExpression Id. */
  int VERSION_STATEMENT = 32;
  /** RegularExpression Id. */
  int VERSION_COMMAND = 33;
  /** RegularExpression Id. */
  int NOREPLY = 34;
  /** RegularExpression Id. */
  int KEY = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUMBER>",
    "<FLAGS>",
    "<TIME>",
    "<LENGTH>",
    "<CREMENT_VALUE>",
    "<CAS_UNIQUE>",
    "\"set\"",
    "\"add\"",
    "\"replace\"",
    "\"append\"",
    "\"prepend\"",
    "\"cas\"",
    "<STORAGE_STATEMENT>",
    "<STORAGE_COMMAND>",
    "<RETRIEVAL_STATEMENT>",
    "<RETRIEVAL_COMMAND>",
    "\"delete\"",
    "<DELETE_COMMAND>",
    "\"incr\"",
    "<INCREMENT_COMMAND>",
    "\"decr\"",
    "<DECREMENT_COMMAND>",
    "\"STAT\"",
    "<STATISTICS_OPTION>",
    "<STATISTICS_COMMAND>",
    "\"flush_all\"",
    "<FLUSH_COMMAND>",
    "\"version\"",
    "<VERSION_COMMAND>",
    "\"noreply\"",
    "<KEY>",
  };

}
