/* Generated By:JavaCC: Do not edit this line. MemcacheParserVisitor.java Version 5.0 */
package hierophant.memcache.jjt;

public interface MemcacheParserVisitor
{
  public hierophant.memcache.Return visit(SimpleNode node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeCommand node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeStorageCommand node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodecreateStorageCommand node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeRetrievalCommand node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeDeleteCommand node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeVersionCommand node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeKey node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeFlags node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeTime node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeLength node, hierophant.memcache.Parameter data);
  public hierophant.memcache.Return visit(NodeNoreply node, hierophant.memcache.Parameter data);
}
/* JavaCC - OriginalChecksum=3a82da455360b19dbe4bfa32507e82ae (do not edit this line) */
