/* Generated By:JJTree: Do not edit this line. NodeLength.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=Node,NODE_EXTENDS=hierophant.memcache.command.Command,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hierophant.memcache.jjt;

public
class NodeLength extends SimpleNode {
  public NodeLength(int id) {
    super(id);
  }

  public NodeLength(MemcacheParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new NodeLength(id);
  }

  public static Node jjtCreate(MemcacheParser p, int id) {
    return new NodeLength(p, id);
  }

  /** Accept the visitor. **/
  public hierophant.memcache.Return jjtAccept(MemcacheParserVisitor visitor, hierophant.memcache.Parameter data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b49b4a330cc7cb3bfd1c6309e4e86eff (do not edit this line) */
