/* Generated By:JJTree: Do not edit this line. NodeTime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=Node,NODE_EXTENDS=hierophant.memcache.command.Command,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hierophant.memcache.jjt;

public
class NodeTime extends SimpleNode {
  public NodeTime(int id) {
    super(id);
  }

  public NodeTime(MemcacheParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new NodeTime(id);
  }

  public static Node jjtCreate(MemcacheParser p, int id) {
    return new NodeTime(p, id);
  }

  /** Accept the visitor. **/
  public hierophant.memcache.Return jjtAccept(MemcacheParserVisitor visitor, hierophant.memcache.Parameter data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dd8b55efb282ef6479b8a5784b28591a (do not edit this line) */
