/* Generated By:JJTree: Do not edit this line. NodeFlags.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=Node,NODE_EXTENDS=hierophant.memcache.command.Command,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hierophant.memcache.jjt;

public
class NodeFlags extends SimpleNode {
  public NodeFlags(int id) {
    super(id);
  }

  public NodeFlags(MemcacheParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new NodeFlags(id);
  }

  public static Node jjtCreate(MemcacheParser p, int id) {
    return new NodeFlags(p, id);
  }

  /** Accept the visitor. **/
  public hierophant.memcache.Return jjtAccept(MemcacheParserVisitor visitor, hierophant.memcache.Parameter data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=31475688a81baa9fca490cabcf7b7944 (do not edit this line) */
