/* Generated By:JJTree: Do not edit this line. NodeRetrievalCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=Node,NODE_EXTENDS=hierophant.memcache.command.Command,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hierophant.memcache.jjt;

public
class NodeRetrievalCommand extends SimpleNode {
  public NodeRetrievalCommand(int id) {
    super(id);
  }

  public NodeRetrievalCommand(MemcacheParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new NodeRetrievalCommand(id);
  }

  public static Node jjtCreate(MemcacheParser p, int id) {
    return new NodeRetrievalCommand(p, id);
  }

  /** Accept the visitor. **/
  public hierophant.memcache.Return jjtAccept(MemcacheParserVisitor visitor, hierophant.memcache.Parameter data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5fc98968e2b6f33c2f2666f212e72c00 (do not edit this line) */
