/* Generated By:JJTree: Do not edit this line. NodeVersionCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=Node,NODE_EXTENDS=hierophant.memcache.command.Command,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hierophant.memcache.jjt;

public
class NodeVersionCommand extends SimpleNode {
  public NodeVersionCommand(int id) {
    super(id);
  }

  public NodeVersionCommand(MemcacheParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new NodeVersionCommand(id);
  }

  public static Node jjtCreate(MemcacheParser p, int id) {
    return new NodeVersionCommand(p, id);
  }

  /** Accept the visitor. **/
  public hierophant.memcache.Return jjtAccept(MemcacheParserVisitor visitor, hierophant.memcache.Parameter data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=610722a6089b8cc5159538da4e4c1f89 (do not edit this line) */
