/* Generated By:JJTree: Do not edit this line. NodeDeleteCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=Node,NODE_EXTENDS=hierophant.memcache.command.Command,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hierophant.memcache.jjt;

public
class NodeDeleteCommand extends SimpleNode {
  public NodeDeleteCommand(int id) {
    super(id);
  }

  public NodeDeleteCommand(MemcacheParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new NodeDeleteCommand(id);
  }

  public static Node jjtCreate(MemcacheParser p, int id) {
    return new NodeDeleteCommand(p, id);
  }

  /** Accept the visitor. **/
  public hierophant.memcache.Return jjtAccept(MemcacheParserVisitor visitor, hierophant.memcache.Parameter data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9bd3cba86ae146a3a9583e8f60cf3890 (do not edit this line) */
