/* Generated By:JJTree: Do not edit this line. NodecreateStorageCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=Node,NODE_EXTENDS=hierophant.memcache.command.Command,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hierophant.memcache.jjt;

public
class NodecreateStorageCommand extends SimpleNode {
  public NodecreateStorageCommand(int id) {
    super(id);
  }

  public NodecreateStorageCommand(MemcacheParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new NodecreateStorageCommand(id);
  }

  public static Node jjtCreate(MemcacheParser p, int id) {
    return new NodecreateStorageCommand(p, id);
  }

  /** Accept the visitor. **/
  public hierophant.memcache.Return jjtAccept(MemcacheParserVisitor visitor, hierophant.memcache.Parameter data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=395355dfdef3c72499751192e33957bd (do not edit this line) */
